<?php
session_set_cookie_params(0,"/","http://localhost/oresoft"); //cross session
session_start();
header('Access-Control-Allow-Origin: *');//ajax cross domain resource
error_reporting(E_ERROR);
$start_time=microtime(true);

include '../includes/baseurl.php';
define("SUB_FOLDER","px-admin/");
$xrout	=	explode('?',curPageURL());
$routing = str_replace(PROX_URL.SUB_FOLDER,'',$xrout[0]);
define("ROUTING",$routing);
 /*** error reporting on ***/
 //error_reporting(E_ALL);
 /*** define the site path **/
//echo get_include_path() ;
$path =realpath(dirname(__FILE__));
//set_include_path($path."/engine");
//set_include_path(get_include_path() . PATH_SEPARATOR . str_replace("px-admin","",$path)."engine");
 define ('PROX_Domain', '..');
 /*** include the init.php file ***/
 include '../includes/init.php';
 /*** load the router ***/
 $registry->router = new router($registry);
 /*** set the controller path ***/
 $registry->router->setPath('controller');
 /*** load up the template ***/
 $registry->template = new template($registry);
 /*** load the controller ***/
$registry->router->loader();

$end_time=microtime(true);
echo "time: ", bcsub($end_time, $start_time, 4), "\n memory (K byte): ", (memory_get_peak_usage(true)/1024), "\n";
/*
<select id="timezone" class="chosen-select" name="timezone" style="display: none;">
																				<option value="Pacific/Midway">
						GMT-10&nbsp;&nbsp;&nbsp;Pacific/Midway					</option>
																				<option value="Pacific/Niue">
						GMT-10&nbsp;&nbsp;&nbsp;Pacific/Niue					</option>
																				<option value="Pacific/Pago_Pago">
						GMT-10&nbsp;&nbsp;&nbsp;Pacific/Pago_Pago					</option>
																				<option value="America/Adak">
						GMT-9&nbsp;&nbsp;&nbsp;America/Adak					</option>
																				<option value="Pacific/Honolulu">
						GMT-9&nbsp;&nbsp;&nbsp;Pacific/Honolulu					</option>
																				<option value="Pacific/Johnston">
						GMT-9&nbsp;&nbsp;&nbsp;Pacific/Johnston					</option>
																				<option value="Pacific/Rarotonga">
						GMT-9&nbsp;&nbsp;&nbsp;Pacific/Rarotonga					</option>
																				<option value="Pacific/Tahiti">
						GMT-9&nbsp;&nbsp;&nbsp;Pacific/Tahiti					</option>
																				<option value="Pacific/Marquesas">
						GMT-8.30&nbsp;Pacific/Marquesas					</option>
																				<option value="America/Anchorage">
						GMT-8&nbsp;&nbsp;&nbsp;America/Anchorage					</option>
																				<option value="America/Juneau">
						GMT-8&nbsp;&nbsp;&nbsp;America/Juneau					</option>
																				<option value="America/Nome">
						GMT-8&nbsp;&nbsp;&nbsp;America/Nome					</option>
																				<option value="America/Sitka">
						GMT-8&nbsp;&nbsp;&nbsp;America/Sitka					</option>
																				<option value="America/Yakutat">
						GMT-8&nbsp;&nbsp;&nbsp;America/Yakutat					</option>
																				<option value="Pacific/Gambier">
						GMT-8&nbsp;&nbsp;&nbsp;Pacific/Gambier					</option>
																				<option value="America/Dawson">
						GMT-7&nbsp;&nbsp;&nbsp;America/Dawson					</option>
																				<option value="America/Los_Angeles">
						GMT-7&nbsp;&nbsp;&nbsp;America/Los_Angeles					</option>
																				<option value="America/Metlakatla">
						GMT-7&nbsp;&nbsp;&nbsp;America/Metlakatla					</option>
																				<option value="America/Santa_Isabel">
						GMT-7&nbsp;&nbsp;&nbsp;America/Santa_Isabel					</option>
																				<option value="America/Tijuana">
						GMT-7&nbsp;&nbsp;&nbsp;America/Tijuana					</option>
																				<option value="America/Vancouver">
						GMT-7&nbsp;&nbsp;&nbsp;America/Vancouver					</option>
																				<option value="America/Whitehorse">
						GMT-7&nbsp;&nbsp;&nbsp;America/Whitehorse					</option>
																				<option value="Pacific/Pitcairn">
						GMT-7&nbsp;&nbsp;&nbsp;Pacific/Pitcairn					</option>
																				<option value="America/Boise">
						GMT-6&nbsp;&nbsp;&nbsp;America/Boise					</option>
																				<option value="America/Cambridge_Bay">
						GMT-6&nbsp;&nbsp;&nbsp;America/Cambridge_Bay					</option>
																				<option value="America/Chihuahua">
						GMT-6&nbsp;&nbsp;&nbsp;America/Chihuahua					</option>
																				<option value="America/Creston">
						GMT-6&nbsp;&nbsp;&nbsp;America/Creston					</option>
																				<option value="America/Dawson_Creek">
						GMT-6&nbsp;&nbsp;&nbsp;America/Dawson_Creek					</option>
																				<option value="America/Denver">
						GMT-6&nbsp;&nbsp;&nbsp;America/Denver					</option>
																				<option value="America/Edmonton">
						GMT-6&nbsp;&nbsp;&nbsp;America/Edmonton					</option>
																				<option value="America/Fort_Nelson">
						GMT-6&nbsp;&nbsp;&nbsp;America/Fort_Nelson					</option>
																				<option value="America/Hermosillo">
						GMT-6&nbsp;&nbsp;&nbsp;America/Hermosillo					</option>
																				<option value="America/Inuvik">
						GMT-6&nbsp;&nbsp;&nbsp;America/Inuvik					</option>
																				<option value="America/Mazatlan">
						GMT-6&nbsp;&nbsp;&nbsp;America/Mazatlan					</option>
																				<option value="America/Ojinaga">
						GMT-6&nbsp;&nbsp;&nbsp;America/Ojinaga					</option>
																				<option value="America/Phoenix">
						GMT-6&nbsp;&nbsp;&nbsp;America/Phoenix					</option>
																				<option value="America/Yellowknife">
						GMT-6&nbsp;&nbsp;&nbsp;America/Yellowknife					</option>
																				<option value="America/Bahia_Banderas">
						GMT-5&nbsp;&nbsp;&nbsp;America/Bahia_Banderas					</option>
																				<option value="America/Belize">
						GMT-5&nbsp;&nbsp;&nbsp;America/Belize					</option>
																				<option value="America/Chicago">
						GMT-5&nbsp;&nbsp;&nbsp;America/Chicago					</option>
																				<option value="America/Costa_Rica">
						GMT-5&nbsp;&nbsp;&nbsp;America/Costa_Rica					</option>
																				<option value="America/El_Salvador">
						GMT-5&nbsp;&nbsp;&nbsp;America/El_Salvador					</option>
																				<option value="America/Guatemala">
						GMT-5&nbsp;&nbsp;&nbsp;America/Guatemala					</option>
																				<option value="America/Indiana/Knox">
						GMT-5&nbsp;&nbsp;&nbsp;America/Indiana/Knox					</option>
																				<option value="America/Indiana/Tell_City">
						GMT-5&nbsp;&nbsp;&nbsp;America/Indiana/Tell_City					</option>
																				<option value="America/Managua">
						GMT-5&nbsp;&nbsp;&nbsp;America/Managua					</option>
																				<option value="America/Matamoros">
						GMT-5&nbsp;&nbsp;&nbsp;America/Matamoros					</option>
																				<option value="America/Menominee">
						GMT-5&nbsp;&nbsp;&nbsp;America/Menominee					</option>
																				<option value="America/Merida">
						GMT-5&nbsp;&nbsp;&nbsp;America/Merida					</option>
																				<option value="America/Mexico_City">
						GMT-5&nbsp;&nbsp;&nbsp;America/Mexico_City					</option>
																				<option value="America/Monterrey">
						GMT-5&nbsp;&nbsp;&nbsp;America/Monterrey					</option>
																				<option value="America/North_Dakota/Beulah">
						GMT-5&nbsp;&nbsp;&nbsp;America/North_Dakota/Beulah					</option>
																				<option value="America/North_Dakota/Center">
						GMT-5&nbsp;&nbsp;&nbsp;America/North_Dakota/Center					</option>
																				<option value="America/North_Dakota/New_Salem">
						GMT-5&nbsp;&nbsp;&nbsp;America/North_Dakota/New_Salem					</option>
																				<option value="America/Rainy_River">
						GMT-5&nbsp;&nbsp;&nbsp;America/Rainy_River					</option>
																				<option value="America/Rankin_Inlet">
						GMT-5&nbsp;&nbsp;&nbsp;America/Rankin_Inlet					</option>
																				<option value="America/Regina">
						GMT-5&nbsp;&nbsp;&nbsp;America/Regina					</option>
																				<option value="America/Resolute">
						GMT-5&nbsp;&nbsp;&nbsp;America/Resolute					</option>
																				<option value="America/Swift_Current">
						GMT-5&nbsp;&nbsp;&nbsp;America/Swift_Current					</option>
																				<option value="America/Tegucigalpa">
						GMT-5&nbsp;&nbsp;&nbsp;America/Tegucigalpa					</option>
																				<option value="America/Winnipeg">
						GMT-5&nbsp;&nbsp;&nbsp;America/Winnipeg					</option>
																				<option value="Pacific/Galapagos">
						GMT-5&nbsp;&nbsp;&nbsp;Pacific/Galapagos					</option>
																				<option value="America/Atikokan">
						GMT-4&nbsp;&nbsp;&nbsp;America/Atikokan					</option>
																				<option value="America/Bogota">
						GMT-4&nbsp;&nbsp;&nbsp;America/Bogota					</option>
																				<option value="America/Cancun">
						GMT-4&nbsp;&nbsp;&nbsp;America/Cancun					</option>
																				<option value="America/Cayman">
						GMT-4&nbsp;&nbsp;&nbsp;America/Cayman					</option>
																				<option value="America/Detroit">
						GMT-4&nbsp;&nbsp;&nbsp;America/Detroit					</option>
																				<option value="America/Eirunepe">
						GMT-4&nbsp;&nbsp;&nbsp;America/Eirunepe					</option>
																				<option value="America/Guayaquil">
						GMT-4&nbsp;&nbsp;&nbsp;America/Guayaquil					</option>
																				<option value="America/Indiana/Indianapolis">
						GMT-4&nbsp;&nbsp;&nbsp;America/Indiana/Indianapolis					</option>
																				<option value="America/Indiana/Marengo">
						GMT-4&nbsp;&nbsp;&nbsp;America/Indiana/Marengo					</option>
																				<option value="America/Indiana/Petersburg">
						GMT-4&nbsp;&nbsp;&nbsp;America/Indiana/Petersburg					</option>
																				<option value="America/Indiana/Vevay">
						GMT-4&nbsp;&nbsp;&nbsp;America/Indiana/Vevay					</option>
																				<option value="America/Indiana/Vincennes">
						GMT-4&nbsp;&nbsp;&nbsp;America/Indiana/Vincennes					</option>
																				<option value="America/Indiana/Winamac">
						GMT-4&nbsp;&nbsp;&nbsp;America/Indiana/Winamac					</option>
																				<option value="America/Iqaluit">
						GMT-4&nbsp;&nbsp;&nbsp;America/Iqaluit					</option>
																				<option value="America/Jamaica">
						GMT-4&nbsp;&nbsp;&nbsp;America/Jamaica					</option>
																				<option value="America/Kentucky/Louisville">
						GMT-4&nbsp;&nbsp;&nbsp;America/Kentucky/Louisville					</option>
																				<option value="America/Kentucky/Monticello">
						GMT-4&nbsp;&nbsp;&nbsp;America/Kentucky/Monticello					</option>
																				<option value="America/Lima">
						GMT-4&nbsp;&nbsp;&nbsp;America/Lima					</option>
																				<option value="America/Nassau">
						GMT-4&nbsp;&nbsp;&nbsp;America/Nassau					</option>
																				<option value="America/New_York">
						GMT-4&nbsp;&nbsp;&nbsp;America/New_York					</option>
																				<option value="America/Nipigon">
						GMT-4&nbsp;&nbsp;&nbsp;America/Nipigon					</option>
																				<option value="America/Panama">
						GMT-4&nbsp;&nbsp;&nbsp;America/Panama					</option>
																				<option value="America/Pangnirtung">
						GMT-4&nbsp;&nbsp;&nbsp;America/Pangnirtung					</option>
																				<option value="America/Port-au-Prince">
						GMT-4&nbsp;&nbsp;&nbsp;America/Port-au-Prince					</option>
																				<option value="America/Rio_Branco">
						GMT-4&nbsp;&nbsp;&nbsp;America/Rio_Branco					</option>
																				<option value="America/Thunder_Bay">
						GMT-4&nbsp;&nbsp;&nbsp;America/Thunder_Bay					</option>
																				<option value="America/Toronto">
						GMT-4&nbsp;&nbsp;&nbsp;America/Toronto					</option>
																				<option value="Pacific/Easter">
						GMT-4&nbsp;&nbsp;&nbsp;Pacific/Easter					</option>
																				<option value="America/Caracas">
						GMT-3.30&nbsp;America/Caracas					</option>
																				<option value="America/Anguilla">
						GMT-3&nbsp;&nbsp;&nbsp;America/Anguilla					</option>
																				<option value="America/Antigua">
						GMT-3&nbsp;&nbsp;&nbsp;America/Antigua					</option>
																				<option value="America/Aruba">
						GMT-3&nbsp;&nbsp;&nbsp;America/Aruba					</option>
																				<option value="America/Barbados">
						GMT-3&nbsp;&nbsp;&nbsp;America/Barbados					</option>
																				<option value="America/Blanc-Sablon">
						GMT-3&nbsp;&nbsp;&nbsp;America/Blanc-Sablon					</option>
																				<option value="America/Boa_Vista">
						GMT-3&nbsp;&nbsp;&nbsp;America/Boa_Vista					</option>
																				<option value="America/Campo_Grande">
						GMT-3&nbsp;&nbsp;&nbsp;America/Campo_Grande					</option>
																				<option value="America/Cuiaba">
						GMT-3&nbsp;&nbsp;&nbsp;America/Cuiaba					</option>
																				<option value="America/Curacao">
						GMT-3&nbsp;&nbsp;&nbsp;America/Curacao					</option>
																				<option value="America/Dominica">
						GMT-3&nbsp;&nbsp;&nbsp;America/Dominica					</option>
																				<option value="America/Glace_Bay">
						GMT-3&nbsp;&nbsp;&nbsp;America/Glace_Bay					</option>
																				<option value="America/Goose_Bay">
						GMT-3&nbsp;&nbsp;&nbsp;America/Goose_Bay					</option>
																				<option value="America/Grand_Turk">
						GMT-3&nbsp;&nbsp;&nbsp;America/Grand_Turk					</option>
																				<option value="America/Grenada">
						GMT-3&nbsp;&nbsp;&nbsp;America/Grenada					</option>
																				<option value="America/Guadeloupe">
						GMT-3&nbsp;&nbsp;&nbsp;America/Guadeloupe					</option>
																				<option value="America/Guyana">
						GMT-3&nbsp;&nbsp;&nbsp;America/Guyana					</option>
																				<option value="America/Halifax">
						GMT-3&nbsp;&nbsp;&nbsp;America/Halifax					</option>
																				<option value="America/Havana">
						GMT-4&nbsp;&nbsp;&nbsp;America/Havana					</option>
																				<option value="America/Kralendijk">
						GMT-3&nbsp;&nbsp;&nbsp;America/Kralendijk					</option>
																				<option value="America/La_Paz">
						GMT-3&nbsp;&nbsp;&nbsp;America/La_Paz					</option>
																				<option value="America/Lower_Princes">
						GMT-3&nbsp;&nbsp;&nbsp;America/Lower_Princes					</option>
																				<option value="America/Manaus">
						GMT-3&nbsp;&nbsp;&nbsp;America/Manaus					</option>
																				<option value="America/Marigot">
						GMT-3&nbsp;&nbsp;&nbsp;America/Marigot					</option>
																				<option value="America/Martinique">
						GMT-3&nbsp;&nbsp;&nbsp;America/Martinique					</option>
																				<option value="America/Moncton">
						GMT-3&nbsp;&nbsp;&nbsp;America/Moncton					</option>
																				<option value="America/Montserrat">
						GMT-3&nbsp;&nbsp;&nbsp;America/Montserrat					</option>
																				<option value="America/Port_of_Spain">
						GMT-3&nbsp;&nbsp;&nbsp;America/Port_of_Spain					</option>
																				<option value="America/Porto_Velho">
						GMT-3&nbsp;&nbsp;&nbsp;America/Porto_Velho					</option>
																				<option value="America/Puerto_Rico">
						GMT-3&nbsp;&nbsp;&nbsp;America/Puerto_Rico					</option>
																				<option value="America/Santo_Domingo">
						GMT-3&nbsp;&nbsp;&nbsp;America/Santo_Domingo					</option>
																				<option value="America/St_Barthelemy">
						GMT-3&nbsp;&nbsp;&nbsp;America/St_Barthelemy					</option>
																				<option value="America/St_Kitts">
						GMT-3&nbsp;&nbsp;&nbsp;America/St_Kitts					</option>
																				<option value="America/St_Lucia">
						GMT-3&nbsp;&nbsp;&nbsp;America/St_Lucia					</option>
																				<option value="America/St_Thomas">
						GMT-3&nbsp;&nbsp;&nbsp;America/St_Thomas					</option>
																				<option value="America/St_Vincent">
						GMT-3&nbsp;&nbsp;&nbsp;America/St_Vincent					</option>
																				<option value="America/Thule">
						GMT-3&nbsp;&nbsp;&nbsp;America/Thule					</option>
																				<option value="America/Tortola">
						GMT-3&nbsp;&nbsp;&nbsp;America/Tortola					</option>
																				<option value="Atlantic/Bermuda">
						GMT-3&nbsp;&nbsp;&nbsp;Atlantic/Bermuda					</option>
																				<option value="America/St_Johns">
						GMT-2.30&nbsp;America/St_Johns					</option>
																				<option value="America/Araguaina">
						GMT-2&nbsp;&nbsp;&nbsp;America/Araguaina					</option>
																				<option value="America/Argentina/Buenos_Aires">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Buenos_Aires					</option>
																				<option value="America/Argentina/Catamarca">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Catamarca					</option>
																				<option value="America/Argentina/Cordoba">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Cordoba					</option>
																				<option value="America/Argentina/Jujuy">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Jujuy					</option>
																				<option value="America/Argentina/La_Rioja">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/La_Rioja					</option>
																				<option value="America/Argentina/Mendoza">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Mendoza					</option>
																				<option value="America/Argentina/Rio_Gallegos">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Rio_Gallegos					</option>
																				<option value="America/Argentina/Salta">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Salta					</option>
																				<option value="America/Argentina/San_Juan">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/San_Juan					</option>
																				<option value="America/Argentina/San_Luis">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/San_Luis					</option>
																				<option value="America/Argentina/Tucuman">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Tucuman					</option>
																				<option value="America/Argentina/Ushuaia">
						GMT-2&nbsp;&nbsp;&nbsp;America/Argentina/Ushuaia					</option>
																				<option value="America/Asuncion">
						GMT-3&nbsp;&nbsp;&nbsp;America/Asuncion					</option>
																				<option value="America/Bahia">
						GMT-2&nbsp;&nbsp;&nbsp;America/Bahia					</option>
																				<option value="America/Belem">
						GMT-2&nbsp;&nbsp;&nbsp;America/Belem					</option>
																				<option value="America/Cayenne">
						GMT-2&nbsp;&nbsp;&nbsp;America/Cayenne					</option>
																				<option value="America/Fortaleza">
						GMT-2&nbsp;&nbsp;&nbsp;America/Fortaleza					</option>
																				<option value="America/Godthab">
						GMT-2&nbsp;&nbsp;&nbsp;America/Godthab					</option>
																				<option value="America/Maceio">
						GMT-2&nbsp;&nbsp;&nbsp;America/Maceio					</option>
																				<option value="America/Montevideo">
						GMT-2&nbsp;&nbsp;&nbsp;America/Montevideo					</option>
																				<option value="America/Paramaribo">
						GMT-2&nbsp;&nbsp;&nbsp;America/Paramaribo					</option>
																				<option value="America/Recife">
						GMT-2&nbsp;&nbsp;&nbsp;America/Recife					</option>
																				<option value="America/Santarem">
						GMT-2&nbsp;&nbsp;&nbsp;America/Santarem					</option>
																				<option value="America/Santiago">
						GMT-2&nbsp;&nbsp;&nbsp;America/Santiago					</option>
																				<option value="America/Sao_Paulo">
						GMT-2&nbsp;&nbsp;&nbsp;America/Sao_Paulo					</option>
																				<option value="Antarctica/Palmer">
						GMT-2&nbsp;&nbsp;&nbsp;Antarctica/Palmer					</option>
																				<option value="Antarctica/Rothera">
						GMT-2&nbsp;&nbsp;&nbsp;Antarctica/Rothera					</option>
																				<option value="Atlantic/Stanley">
						GMT-2&nbsp;&nbsp;&nbsp;Atlantic/Stanley					</option>
																				<option value="America/Miquelon">
						GMT-2&nbsp;&nbsp;&nbsp;America/Miquelon					</option>
																				<option value="America/Noronha">
						GMT-1&nbsp;&nbsp;&nbsp;America/Noronha					</option>
																				<option value="Atlantic/South_Georgia">
						GMT-1&nbsp;&nbsp;&nbsp;Atlantic/South_Georgia					</option>
																				<option value="America/Scoresbysund">
						GMT-0&nbsp;&nbsp;&nbsp;America/Scoresbysund					</option>
																				<option value="Atlantic/Azores">
						GMT-0&nbsp;&nbsp;&nbsp;Atlantic/Azores					</option>
																				<option value="Atlantic/Cape_Verde">
						GMT-0&nbsp;&nbsp;&nbsp;Atlantic/Cape_Verde					</option>
																				<option value="Africa/Abidjan">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Abidjan					</option>
																				<option value="Africa/Accra">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Accra					</option>
																				<option value="Africa/Bamako">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Bamako					</option>
																				<option value="Africa/Banjul">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Banjul					</option>
																				<option value="Africa/Bissau">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Bissau					</option>
																				<option value="Africa/Casablanca">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Casablanca					</option>
																				<option value="Africa/Conakry">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Conakry					</option>
																				<option value="Africa/Dakar">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Dakar					</option>
																				<option value="Africa/El_Aaiun">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/El_Aaiun					</option>
																				<option value="Africa/Freetown">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Freetown					</option>
																				<option value="Africa/Lome">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Lome					</option>
																				<option value="Africa/Monrovia">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Monrovia					</option>
																				<option value="Africa/Nouakchott">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Nouakchott					</option>
																				<option value="Africa/Ouagadougou">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Ouagadougou					</option>
																				<option value="Africa/Sao_Tome">
						GMT -1&nbsp;&nbsp;&nbsp;Africa/Sao_Tome					</option>
																				<option value="America/Danmarkshavn">
						GMT -1&nbsp;&nbsp;&nbsp;America/Danmarkshavn					</option>
																				<option value="Antarctica/Troll">
						GMT -1&nbsp;&nbsp;&nbsp;Antarctica/Troll					</option>
																				<option value="Atlantic/Canary">
						GMT -1&nbsp;&nbsp;&nbsp;Atlantic/Canary					</option>
																				<option value="Atlantic/Faroe">
						GMT -1&nbsp;&nbsp;&nbsp;Atlantic/Faroe					</option>
																				<option value="Atlantic/Madeira">
						GMT -1&nbsp;&nbsp;&nbsp;Atlantic/Madeira					</option>
																				<option value="Atlantic/Reykjavik">
						GMT -1&nbsp;&nbsp;&nbsp;Atlantic/Reykjavik					</option>
																				<option value="Atlantic/St_Helena">
						GMT -1&nbsp;&nbsp;&nbsp;Atlantic/St_Helena					</option>
																				<option value="Europe/Dublin">
						GMT -1&nbsp;&nbsp;&nbsp;Europe/Dublin					</option>
																				<option value="Europe/Guernsey">
						GMT -1&nbsp;&nbsp;&nbsp;Europe/Guernsey					</option>
																				<option value="Europe/Isle_of_Man">
						GMT -1&nbsp;&nbsp;&nbsp;Europe/Isle_of_Man					</option>
																				<option value="Europe/Jersey">
						GMT -1&nbsp;&nbsp;&nbsp;Europe/Jersey					</option>
																				<option value="Europe/Lisbon">
						GMT -1&nbsp;&nbsp;&nbsp;Europe/Lisbon					</option>
																				<option value="Europe/London">
						GMT -1&nbsp;&nbsp;&nbsp;Europe/London					</option>
																				<option value="UTC">
						GMT -1&nbsp;&nbsp;&nbsp;UTC					</option>
																				<option value="Africa/Algiers">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Algiers					</option>
																				<option value="Africa/Bangui">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Bangui					</option>
																				<option value="Africa/Brazzaville">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Brazzaville					</option>
																				<option value="Africa/Ceuta">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Ceuta					</option>
																				<option value="Africa/Douala">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Douala					</option>
																				<option value="Africa/Kinshasa">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Kinshasa					</option>
																				<option value="Africa/Lagos">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Lagos					</option>
																				<option value="Africa/Libreville">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Libreville					</option>
																				<option value="Africa/Luanda">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Luanda					</option>
																				<option value="Africa/Malabo">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Malabo					</option>
																				<option value="Africa/Ndjamena">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Ndjamena					</option>
																				<option value="Africa/Niamey">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Niamey					</option>
																				<option value="Africa/Porto-Novo">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Porto-Novo					</option>
																				<option value="Africa/Tunis">
						GMT+0&nbsp;&nbsp;&nbsp;Africa/Tunis					</option>
																				<option value="Arctic/Longyearbyen">
						GMT+0&nbsp;&nbsp;&nbsp;Arctic/Longyearbyen					</option>
																				<option value="Europe/Amsterdam">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Amsterdam					</option>
																				<option value="Europe/Andorra">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Andorra					</option>
																				<option value="Europe/Belgrade">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Belgrade					</option>
																				<option value="Europe/Berlin">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Berlin					</option>
																				<option value="Europe/Bratislava">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Bratislava					</option>
																				<option value="Europe/Brussels">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Brussels					</option>
																				<option value="Europe/Budapest">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Budapest					</option>
																				<option value="Europe/Busingen">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Busingen					</option>
																				<option value="Europe/Copenhagen">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Copenhagen					</option>
																				<option value="Europe/Gibraltar">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Gibraltar					</option>
																				<option value="Europe/Ljubljana">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Ljubljana					</option>
																				<option value="Europe/Luxembourg">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Luxembourg					</option>
																				<option value="Europe/Madrid">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Madrid					</option>
																				<option value="Europe/Malta">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Malta					</option>
																				<option value="Europe/Monaco">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Monaco					</option>
																				<option value="Europe/Oslo">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Oslo					</option>
																				<option value="Europe/Paris">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Paris					</option>
																				<option value="Europe/Podgorica">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Podgorica					</option>
																				<option value="Europe/Prague">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Prague					</option>
																				<option value="Europe/Rome">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Rome					</option>
																				<option value="Europe/San_Marino">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/San_Marino					</option>
																				<option value="Europe/Sarajevo">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Sarajevo					</option>
																				<option value="Europe/Skopje">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Skopje					</option>
																				<option value="Europe/Stockholm">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Stockholm					</option>
																				<option value="Europe/Tirane">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Tirane					</option>
																				<option value="Europe/Vaduz">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Vaduz					</option>
																				<option value="Europe/Vatican">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Vatican					</option>
																				<option value="Europe/Vienna">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Vienna					</option>
																				<option value="Europe/Warsaw">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Warsaw					</option>
																				<option value="Europe/Zagreb">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Zagreb					</option>
																				<option value="Europe/Zurich">
						GMT+0&nbsp;&nbsp;&nbsp;Europe/Zurich					</option>
																				<option value="Africa/Blantyre">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Blantyre					</option>
																				<option value="Africa/Bujumbura">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Bujumbura					</option>
																				<option value="Africa/Cairo">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Cairo					</option>
																				<option value="Africa/Gaborone">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Gaborone					</option>
																				<option value="Africa/Harare">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Harare					</option>
																				<option value="Africa/Johannesburg">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Johannesburg					</option>
																				<option value="Africa/Kigali">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Kigali					</option>
																				<option value="Africa/Lubumbashi">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Lubumbashi					</option>
																				<option value="Africa/Lusaka">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Lusaka					</option>
																				<option value="Africa/Maputo">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Maputo					</option>
																				<option value="Africa/Maseru">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Maseru					</option>
																				<option value="Africa/Mbabane">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Mbabane					</option>
																				<option value="Africa/Tripoli">
						GMT+1&nbsp;&nbsp;&nbsp;Africa/Tripoli					</option>
																				<option value="Africa/Windhoek">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Windhoek					</option>
																				<option value="Asia/Amman">
						GMT+1&nbsp;&nbsp;&nbsp;Asia/Amman					</option>
																				<option value="Asia/Beirut">
						GMT+1&nbsp;&nbsp;&nbsp;Asia/Beirut					</option>
																				<option value="Asia/Damascus">
						GMT+1&nbsp;&nbsp;&nbsp;Asia/Damascus					</option>
																				<option value="Asia/Gaza">
						GMT+1&nbsp;&nbsp;&nbsp;Asia/Gaza					</option>
																				<option value="Asia/Hebron">
						GMT+1&nbsp;&nbsp;&nbsp;Asia/Hebron					</option>
																				<option value="Asia/Jerusalem">
						GMT+1&nbsp;&nbsp;&nbsp;Asia/Jerusalem					</option>
																				<option value="Asia/Nicosia">
						GMT+1&nbsp;&nbsp;&nbsp;Asia/Nicosia					</option>
																				<option value="Europe/Athens">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Athens					</option>
																				<option value="Europe/Bucharest">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Bucharest					</option>
																				<option value="Europe/Chisinau">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Chisinau					</option>
																				<option value="Europe/Helsinki">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Helsinki					</option>
																				<option value="Europe/Istanbul">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Istanbul					</option>
																				<option value="Europe/Kaliningrad">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Kaliningrad					</option>
																				<option value="Europe/Kiev">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Kiev					</option>
																				<option value="Europe/Mariehamn">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Mariehamn					</option>
																				<option value="Europe/Riga">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Riga					</option>
																				<option value="Europe/Sofia">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Sofia					</option>
																				<option value="Europe/Tallinn">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Tallinn					</option>
																				<option value="Europe/Uzhgorod">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Uzhgorod					</option>
																				<option value="Europe/Vilnius">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Vilnius					</option>
																				<option value="Europe/Zaporozhye">
						GMT+1&nbsp;&nbsp;&nbsp;Europe/Zaporozhye					</option>
																				<option value="Africa/Addis_Ababa">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Addis_Ababa					</option>
																				<option value="Africa/Asmara">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Asmara					</option>
																				<option value="Africa/Dar_es_Salaam">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Dar_es_Salaam					</option>
																				<option value="Africa/Djibouti">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Djibouti					</option>
																				<option value="Africa/Juba">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Juba					</option>
																				<option value="Africa/Kampala">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Kampala					</option>
																				<option value="Africa/Khartoum">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Khartoum					</option>
																				<option value="Africa/Mogadishu">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Mogadishu					</option>
																				<option value="Africa/Nairobi">
						GMT+2&nbsp;&nbsp;&nbsp;Africa/Nairobi					</option>
																				<option value="Antarctica/Syowa">
						GMT+2&nbsp;&nbsp;&nbsp;Antarctica/Syowa					</option>
																				<option value="Asia/Aden">
						GMT+2&nbsp;&nbsp;&nbsp;Asia/Aden					</option>
																				<option value="Asia/Baghdad">
						GMT+2&nbsp;&nbsp;&nbsp;Asia/Baghdad					</option>
																				<option value="Asia/Bahrain">
						GMT+2&nbsp;&nbsp;&nbsp;Asia/Bahrain					</option>
																				<option value="Asia/Kuwait">
						GMT+2&nbsp;&nbsp;&nbsp;Asia/Kuwait					</option>
																				<option value="Asia/Qatar">
						GMT+2&nbsp;&nbsp;&nbsp;Asia/Qatar					</option>
																				<option value="Asia/Riyadh">
						GMT+2&nbsp;&nbsp;&nbsp;Asia/Riyadh					</option>
																				<option value="Europe/Minsk">
						GMT+2&nbsp;&nbsp;&nbsp;Europe/Minsk					</option>
																				<option value="Europe/Moscow">
						GMT+2&nbsp;&nbsp;&nbsp;Europe/Moscow					</option>
																				<option value="Europe/Simferopol">
						GMT+2&nbsp;&nbsp;&nbsp;Europe/Simferopol					</option>
																				<option value="Europe/Volgograd">
						GMT+2&nbsp;&nbsp;&nbsp;Europe/Volgograd					</option>
																				<option value="Indian/Antananarivo">
						GMT+2&nbsp;&nbsp;&nbsp;Indian/Antananarivo					</option>
																				<option value="Indian/Comoro">
						GMT+2&nbsp;&nbsp;&nbsp;Indian/Comoro					</option>
																				<option value="Indian/Mayotte">
						GMT+2&nbsp;&nbsp;&nbsp;Indian/Mayotte					</option>
																				<option value="Asia/Tehran">
						GMT+2.30&nbsp;Asia/Tehran					</option>
																				<option value="Asia/Baku">
						GMT+3&nbsp;&nbsp;&nbsp;Asia/Baku					</option>
																				<option value="Asia/Dubai">
						GMT+3&nbsp;&nbsp;&nbsp;Asia/Dubai					</option>
																				<option value="Asia/Muscat">
						GMT+3&nbsp;&nbsp;&nbsp;Asia/Muscat					</option>
																				<option value="Asia/Tbilisi">
						GMT+3&nbsp;&nbsp;&nbsp;Asia/Tbilisi					</option>
																				<option value="Asia/Yerevan">
						GMT+3&nbsp;&nbsp;&nbsp;Asia/Yerevan					</option>
																				<option value="Europe/Samara">
						GMT+3&nbsp;&nbsp;&nbsp;Europe/Samara					</option>
																				<option value="Indian/Mahe">
						GMT+3&nbsp;&nbsp;&nbsp;Indian/Mahe					</option>
																				<option value="Indian/Mauritius">
						GMT+3&nbsp;&nbsp;&nbsp;Indian/Mauritius					</option>
																				<option value="Indian/Reunion">
						GMT+3&nbsp;&nbsp;&nbsp;Indian/Reunion					</option>
																				<option value="Asia/Kabul">
						GMT+3.30&nbsp;Asia/Kabul					</option>
																				<option value="Antarctica/Mawson">
						GMT+4&nbsp;&nbsp;&nbsp;Antarctica/Mawson					</option>
																				<option value="Asia/Aqtau">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Aqtau					</option>
																				<option value="Asia/Aqtobe">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Aqtobe					</option>
																				<option value="Asia/Ashgabat">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Ashgabat					</option>
																				<option value="Asia/Dushanbe">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Dushanbe					</option>
																				<option value="Asia/Karachi">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Karachi					</option>
																				<option value="Asia/Oral">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Oral					</option>
																				<option value="Asia/Samarkand">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Samarkand					</option>
																				<option value="Asia/Tashkent">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Tashkent					</option>
																				<option value="Asia/Yekaterinburg">
						GMT+4&nbsp;&nbsp;&nbsp;Asia/Yekaterinburg					</option>
																				<option value="Indian/Kerguelen">
						GMT+4&nbsp;&nbsp;&nbsp;Indian/Kerguelen					</option>
																				<option value="Indian/Maldives">
						GMT+4&nbsp;&nbsp;&nbsp;Indian/Maldives					</option>
																				<option value="Asia/Colombo">
						GMT+4.30&nbsp;Asia/Colombo					</option>
																				<option value="Asia/Kolkata">
						GMT+4.30&nbsp;Asia/Kolkata					</option>
																				<option value="Asia/Kathmandu">
						GMT+4.45&nbsp;Asia/Kathmandu					</option>
																				<option value="Antarctica/Vostok">
						GMT+5&nbsp;&nbsp;&nbsp;Antarctica/Vostok					</option>
																				<option value="Asia/Almaty">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Almaty					</option>
																				<option value="Asia/Bishkek">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Bishkek					</option>
																				<option value="Asia/Dhaka">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Dhaka					</option>
																				<option value="Asia/Novosibirsk">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Novosibirsk					</option>
																				<option value="Asia/Omsk">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Omsk					</option>
																				<option value="Asia/Qyzylorda">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Qyzylorda					</option>
																				<option value="Asia/Thimphu">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Thimphu					</option>
																				<option value="Asia/Urumqi">
						GMT+5&nbsp;&nbsp;&nbsp;Asia/Urumqi					</option>
																				<option value="Indian/Chagos">
						GMT+5&nbsp;&nbsp;&nbsp;Indian/Chagos					</option>
																				<option value="Asia/Rangoon">
						GMT+5.30&nbsp;Asia/Rangoon					</option>
																				<option value="Indian/Cocos">
						GMT+5.30&nbsp;Indian/Cocos					</option>
																				<option value="Antarctica/Davis">
						GMT+6&nbsp;&nbsp;&nbsp;Antarctica/Davis					</option>
																				<option value="Asia/Bangkok">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Bangkok					</option>
																				<option value="Asia/Ho_Chi_Minh">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Ho_Chi_Minh					</option>
																				<option value="Asia/Hovd">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Hovd					</option>
																				<option value="Asia/Jakarta">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Jakarta					</option>
																				<option value="Asia/Krasnoyarsk">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Krasnoyarsk					</option>
																				<option value="Asia/Novokuznetsk">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Novokuznetsk					</option>
																				<option value="Asia/Phnom_Penh">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Phnom_Penh					</option>
																				<option value="Asia/Pontianak">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Pontianak					</option>
																				<option value="Asia/Vientiane">
						GMT+6&nbsp;&nbsp;&nbsp;Asia/Vientiane					</option>
																				<option value="Indian/Christmas">
						GMT+6&nbsp;&nbsp;&nbsp;Indian/Christmas					</option>
																				<option value="Antarctica/Casey">
						GMT+7&nbsp;&nbsp;&nbsp;Antarctica/Casey					</option>
																				<option value="Asia/Brunei">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Brunei					</option>
																				<option value="Asia/Chita">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Chita					</option>
																				<option value="Asia/Choibalsan">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Choibalsan					</option>
																				<option value="Asia/Hong_Kong">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Hong_Kong					</option>
																				<option value="Asia/Irkutsk">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Irkutsk					</option>
																				<option value="Asia/Kuala_Lumpur">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Kuala_Lumpur					</option>
																				<option value="Asia/Kuching">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Kuching					</option>
																				<option value="Asia/Macau">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Macau					</option>
																				<option value="Asia/Makassar">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Makassar					</option>
																				<option value="Asia/Manila">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Manila					</option>
																				<option value="Asia/Shanghai">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Shanghai					</option>
																				<option value="Asia/Singapore">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Singapore					</option>
																				<option value="Asia/Taipei">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Taipei					</option>
																				<option value="Asia/Ulaanbaatar">
						GMT+7&nbsp;&nbsp;&nbsp;Asia/Ulaanbaatar					</option>
																				<option value="Australia/Perth">
						GMT+7&nbsp;&nbsp;&nbsp;Australia/Perth					</option>
																				<option value="Asia/Pyongyang">
						GMT+7.30&nbsp;Asia/Pyongyang					</option>
																				<option value="Australia/Eucla">
						GMT+7.45&nbsp;Australia/Eucla					</option>
																				<option value="Asia/Dili">
						GMT+8&nbsp;&nbsp;&nbsp;Asia/Dili					</option>
																				<option value="Asia/Jayapura">
						GMT+8&nbsp;&nbsp;&nbsp;Asia/Jayapura					</option>
																				<option value="Asia/Khandyga">
						GMT+8&nbsp;&nbsp;&nbsp;Asia/Khandyga					</option>
																				<option value="Asia/Seoul">
						GMT+8&nbsp;&nbsp;&nbsp;Asia/Seoul					</option>
																				<option value="Asia/Tokyo">
						GMT+8&nbsp;&nbsp;&nbsp;Asia/Tokyo					</option>
																				<option value="Asia/Yakutsk">
						GMT+8&nbsp;&nbsp;&nbsp;Asia/Yakutsk					</option>
																				<option value="Pacific/Palau">
						GMT+8&nbsp;&nbsp;&nbsp;Pacific/Palau					</option>
																				<option value="Australia/Darwin">
						GMT+8.30&nbsp;Australia/Darwin					</option>
																				<option value="Antarctica/DumontDUrville">
						GMT+9&nbsp;&nbsp;&nbsp;Antarctica/DumontDUrville					</option>
																				<option value="Asia/Magadan">
						GMT+9&nbsp;&nbsp;&nbsp;Asia/Magadan					</option>
																				<option value="Asia/Sakhalin">
						GMT+9&nbsp;&nbsp;&nbsp;Asia/Sakhalin					</option>
																				<option value="Asia/Ust-Nera">
						GMT+9&nbsp;&nbsp;&nbsp;Asia/Ust-Nera					</option>
																				<option value="Asia/Vladivostok">
						GMT+9&nbsp;&nbsp;&nbsp;Asia/Vladivostok					</option>
																				<option value="Australia/Brisbane">
						GMT+9&nbsp;&nbsp;&nbsp;Australia/Brisbane					</option>
																				<option value="Australia/Lindeman">
						GMT+9&nbsp;&nbsp;&nbsp;Australia/Lindeman					</option>
																				<option value="Pacific/Chuuk">
						GMT+9&nbsp;&nbsp;&nbsp;Pacific/Chuuk					</option>
																				<option value="Pacific/Guam">
						GMT+9&nbsp;&nbsp;&nbsp;Pacific/Guam					</option>
																				<option value="Pacific/Port_Moresby">
						GMT+9&nbsp;&nbsp;&nbsp;Pacific/Port_Moresby					</option>
																				<option value="Pacific/Saipan">
						GMT+9&nbsp;&nbsp;&nbsp;Pacific/Saipan					</option>
																				<option value="Australia/Adelaide">
						GMT+10.30&nbsp;Australia/Adelaide					</option>
																				<option value="Australia/Broken_Hill">
						GMT+10.30&nbsp;Australia/Broken_Hill					</option>
																				<option value="Antarctica/Macquarie">
						GMT+10&nbsp;&nbsp;&nbsp;Antarctica/Macquarie					</option>
																				<option value="Asia/Srednekolymsk">
						GMT+10&nbsp;&nbsp;&nbsp;Asia/Srednekolymsk					</option>
																				<option value="Australia/Currie">
						GMT+11&nbsp;&nbsp;&nbsp;Australia/Currie					</option>
																				<option value="Australia/Hobart">
						GMT+11&nbsp;&nbsp;&nbsp;Australia/Hobart					</option>
																				<option value="Australia/Lord_Howe">
						GMT+11&nbsp;&nbsp;&nbsp;Australia/Lord_Howe					</option>
																				<option value="Australia/Melbourne">
						GMT+11&nbsp;&nbsp;&nbsp;Australia/Melbourne					</option>
																				<option value="Australia/Sydney">
						GMT+11&nbsp;&nbsp;&nbsp;Australia/Sydney					</option>
																				<option value="Pacific/Bougainville">
						GMT+10&nbsp;&nbsp;&nbsp;Pacific/Bougainville					</option>
																				<option value="Pacific/Efate">
						GMT+10&nbsp;&nbsp;&nbsp;Pacific/Efate					</option>
																				<option value="Pacific/Guadalcanal">
						GMT+10&nbsp;&nbsp;&nbsp;Pacific/Guadalcanal					</option>
																				<option value="Pacific/Kosrae">
						GMT+10&nbsp;&nbsp;&nbsp;Pacific/Kosrae					</option>
																				<option value="Pacific/Norfolk">
						GMT+10&nbsp;&nbsp;&nbsp;Pacific/Norfolk					</option>
																				<option value="Pacific/Noumea">
						GMT+10&nbsp;&nbsp;&nbsp;Pacific/Noumea					</option>
																				<option value="Pacific/Pohnpei">
						GMT+10&nbsp;&nbsp;&nbsp;Pacific/Pohnpei					</option>
																				<option value="Asia/Anadyr">
						GMT+11&nbsp;&nbsp;&nbsp;Asia/Anadyr					</option>
																				<option value="Asia/Kamchatka">
						GMT+11&nbsp;&nbsp;&nbsp;Asia/Kamchatka					</option>
																				<option value="Pacific/Fiji">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Fiji					</option>
																				<option value="Pacific/Funafuti">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Funafuti					</option>
																				<option value="Pacific/Kwajalein">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Kwajalein					</option>
																				<option value="Pacific/Majuro">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Majuro					</option>
																				<option value="Pacific/Nauru">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Nauru					</option>
																				<option value="Pacific/Tarawa">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Tarawa					</option>
																				<option value="Pacific/Wake">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Wake					</option>
																				<option value="Pacific/Wallis">
						GMT+11&nbsp;&nbsp;&nbsp;Pacific/Wallis					</option>
																				<option value="Antarctica/McMurdo">
						GMT+13&nbsp;&nbsp;&nbsp;Antarctica/McMurdo					</option>
																				<option value="Pacific/Auckland">
						GMT+13&nbsp;&nbsp;&nbsp;Pacific/Auckland					</option>
																				<option value="Pacific/Enderbury">
						GMT+12&nbsp;&nbsp;&nbsp;Pacific/Enderbury					</option>
																				<option value="Pacific/Fakaofo">
						GMT+12&nbsp;&nbsp;&nbsp;Pacific/Fakaofo					</option>
																				<option value="Pacific/Tongatapu">
						GMT+12&nbsp;&nbsp;&nbsp;Pacific/Tongatapu					</option>
																				<option value="Pacific/Chatham">
						GMT+13.45&nbsp;Pacific/Chatham					</option>
																				<option value="Pacific/Apia">
						GMT+14&nbsp;&nbsp;&nbsp;Pacific/Apia					</option>
																				<option value="Pacific/Kiritimati">
						GMT+13&nbsp;&nbsp;&nbsp;Pacific/Kiritimati					</option>
														</select>
*/
?>
